### ISSUE TITLE
Failed pattern match in uncons

### ISSUE THREAD

**Issue by ethul** [ethul/purescript-catenable-lists#1]
```bash
Error: Failed pattern match: DList
    at Object.uncons (/path/purescript/purescript-free-bench/output/Data.DList/index.js:36:15)
    at /path/purescript/purescript-free-bench/output/Data.CList/index.js:97:46
    at /path/purescript/purescript-free-bench/output/Data.CList/index.js:118:29
    at linkAll (/path/purescript/purescript-free-bench/output/Data.CList/index.js:130:35)
    at /path/purescript/purescript-free-bench/output/Data.CList/index.js:143:24
    at Object.uncons (/path/purescript/purescript-free-bench/output/Data.CList/index.js:146:11)
    at toView (/path/purescript/purescript-free-bench/output/Control.Monad.Free/index.js:67:34)
    at go (/path/purescript/purescript-free-bench/output/Control.Monad.Free/index.js:90:27)
    at /path/purescript/purescript-free-bench/output/Prelude/index.js:175:22
    at go (/path/purescript/purescript-free-bench/output/Control.Monad.Rec.Class/index.js:93:38)
```

**Comment by ethul** [comment]
See if this is still an issue after reverting to the strict version
